// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/open-cluster-management/api/addon/v1alpha1"
	scheme "github.com/open-cluster-management/api/client/addon/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterManagerAddOnsGetter has a method to return a ClusterManagerAddOnInterface.
// A group's client should implement this interface.
type ClusterManagerAddOnsGetter interface {
	ClusterManagerAddOns() ClusterManagerAddOnInterface
}

// ClusterManagerAddOnInterface has methods to work with ClusterManagerAddOn resources.
type ClusterManagerAddOnInterface interface {
	Create(ctx context.Context, clusterManagerAddOn *v1alpha1.ClusterManagerAddOn, opts v1.CreateOptions) (*v1alpha1.ClusterManagerAddOn, error)
	Update(ctx context.Context, clusterManagerAddOn *v1alpha1.ClusterManagerAddOn, opts v1.UpdateOptions) (*v1alpha1.ClusterManagerAddOn, error)
	UpdateStatus(ctx context.Context, clusterManagerAddOn *v1alpha1.ClusterManagerAddOn, opts v1.UpdateOptions) (*v1alpha1.ClusterManagerAddOn, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ClusterManagerAddOn, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ClusterManagerAddOnList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterManagerAddOn, err error)
	ClusterManagerAddOnExpansion
}

// clusterManagerAddOns implements ClusterManagerAddOnInterface
type clusterManagerAddOns struct {
	client rest.Interface
}

// newClusterManagerAddOns returns a ClusterManagerAddOns
func newClusterManagerAddOns(c *AddonV1alpha1Client) *clusterManagerAddOns {
	return &clusterManagerAddOns{
		client: c.RESTClient(),
	}
}

// Get takes name of the clusterManagerAddOn, and returns the corresponding clusterManagerAddOn object, and an error if there is any.
func (c *clusterManagerAddOns) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterManagerAddOn, err error) {
	result = &v1alpha1.ClusterManagerAddOn{}
	err = c.client.Get().
		Resource("clustermanageraddons").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterManagerAddOns that match those selectors.
func (c *clusterManagerAddOns) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterManagerAddOnList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ClusterManagerAddOnList{}
	err = c.client.Get().
		Resource("clustermanageraddons").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterManagerAddOns.
func (c *clusterManagerAddOns) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("clustermanageraddons").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clusterManagerAddOn and creates it.  Returns the server's representation of the clusterManagerAddOn, and an error, if there is any.
func (c *clusterManagerAddOns) Create(ctx context.Context, clusterManagerAddOn *v1alpha1.ClusterManagerAddOn, opts v1.CreateOptions) (result *v1alpha1.ClusterManagerAddOn, err error) {
	result = &v1alpha1.ClusterManagerAddOn{}
	err = c.client.Post().
		Resource("clustermanageraddons").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterManagerAddOn).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clusterManagerAddOn and updates it. Returns the server's representation of the clusterManagerAddOn, and an error, if there is any.
func (c *clusterManagerAddOns) Update(ctx context.Context, clusterManagerAddOn *v1alpha1.ClusterManagerAddOn, opts v1.UpdateOptions) (result *v1alpha1.ClusterManagerAddOn, err error) {
	result = &v1alpha1.ClusterManagerAddOn{}
	err = c.client.Put().
		Resource("clustermanageraddons").
		Name(clusterManagerAddOn.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterManagerAddOn).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *clusterManagerAddOns) UpdateStatus(ctx context.Context, clusterManagerAddOn *v1alpha1.ClusterManagerAddOn, opts v1.UpdateOptions) (result *v1alpha1.ClusterManagerAddOn, err error) {
	result = &v1alpha1.ClusterManagerAddOn{}
	err = c.client.Put().
		Resource("clustermanageraddons").
		Name(clusterManagerAddOn.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterManagerAddOn).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clusterManagerAddOn and deletes it. Returns an error if one occurs.
func (c *clusterManagerAddOns) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("clustermanageraddons").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterManagerAddOns) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("clustermanageraddons").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clusterManagerAddOn.
func (c *clusterManagerAddOns) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterManagerAddOn, err error) {
	result = &v1alpha1.ClusterManagerAddOn{}
	err = c.client.Patch(pt).
		Resource("clustermanageraddons").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
