apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: clustermanagementaddons.addon.open-cluster-management.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.displayName
    name: DISPLAY NAME
    type: string
  - JSONPath: .spec.addOnConfigCRD
    name: CRD NAME
    type: string
  group: addon.open-cluster-management.io
  names:
    kind: ClusterManagementAddOn
    listKind: ClusterManagementAddOnList
    plural: clustermanagementaddons
    singular: clustermanagementaddon
  preserveUnknownFields: false
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ClusterManagementAddOn represents the registration of an add-on
        to the cluster management. This resource allows the user to discover which
        add-on is available for the cluster management and also provides metadata
        information about the add-on. The resource also provides a linkage to ManagedClusterAddOn,
        the name of the ClusterManagementAddOn resource will be used for the namespace-scoped
        ManagedClusterAddOn resource ClusterManagementAddOn is a cluster-scoped resource.
      type: object
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Spec represents a desired configuration for the agent on the
            cluster management add-on.
          type: object
          properties:
            addOnConfigCRD:
              description: 'AddOnConfigCRD is a reference to the name of the CRD that
                configures the add-on Note: There may be a case where a single add-on
                config CRD controls multiple related add-ons, in this case multiple
                ClusterManagementAddOn resource should be created.'
              type: string
            description:
              description: Description represents the detailed description of the
                add-on.
              type: string
            displayName:
              description: DisplayName represents the name that will be displayed.
              type: string
        status:
          description: Status represents the current status of cluster management
            add-on.
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
