// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/open-cluster-management/api/addon/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ClusterManagerAddOnLister helps list ClusterManagerAddOns.
type ClusterManagerAddOnLister interface {
	// List lists all ClusterManagerAddOns in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.ClusterManagerAddOn, err error)
	// Get retrieves the ClusterManagerAddOn from the index for a given name.
	Get(name string) (*v1alpha1.ClusterManagerAddOn, error)
	ClusterManagerAddOnListerExpansion
}

// clusterManagerAddOnLister implements the ClusterManagerAddOnLister interface.
type clusterManagerAddOnLister struct {
	indexer cache.Indexer
}

// NewClusterManagerAddOnLister returns a new ClusterManagerAddOnLister.
func NewClusterManagerAddOnLister(indexer cache.Indexer) ClusterManagerAddOnLister {
	return &clusterManagerAddOnLister{indexer: indexer}
}

// List lists all ClusterManagerAddOns in the indexer.
func (s *clusterManagerAddOnLister) List(selector labels.Selector) (ret []*v1alpha1.ClusterManagerAddOn, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ClusterManagerAddOn))
	})
	return ret, err
}

// Get retrieves the ClusterManagerAddOn from the index for a given name.
func (s *clusterManagerAddOnLister) Get(name string) (*v1alpha1.ClusterManagerAddOn, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("clustermanageraddon"), name)
	}
	return obj.(*v1alpha1.ClusterManagerAddOn), nil
}
