// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ClusterManagerAddOnListerExpansion allows custom methods to be added to
// ClusterManagerAddOnLister.
type ClusterManagerAddOnListerExpansion interface{}

// ManagedClusterAddOnListerExpansion allows custom methods to be added to
// ManagedClusterAddOnLister.
type ManagedClusterAddOnListerExpansion interface{}

// ManagedClusterAddOnNamespaceListerExpansion allows custom methods to be added to
// ManagedClusterAddOnNamespaceLister.
type ManagedClusterAddOnNamespaceListerExpansion interface{}
