// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/open-cluster-management/api/addon/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterManagerAddOns implements ClusterManagerAddOnInterface
type FakeClusterManagerAddOns struct {
	Fake *FakeAddonV1alpha1
}

var clustermanageraddonsResource = schema.GroupVersionResource{Group: "addon.open-cluster-management.io", Version: "v1alpha1", Resource: "clustermanageraddons"}

var clustermanageraddonsKind = schema.GroupVersionKind{Group: "addon.open-cluster-management.io", Version: "v1alpha1", Kind: "ClusterManagerAddOn"}

// Get takes name of the clusterManagerAddOn, and returns the corresponding clusterManagerAddOn object, and an error if there is any.
func (c *FakeClusterManagerAddOns) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterManagerAddOn, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clustermanageraddonsResource, name), &v1alpha1.ClusterManagerAddOn{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterManagerAddOn), err
}

// List takes label and field selectors, and returns the list of ClusterManagerAddOns that match those selectors.
func (c *FakeClusterManagerAddOns) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterManagerAddOnList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clustermanageraddonsResource, clustermanageraddonsKind, opts), &v1alpha1.ClusterManagerAddOnList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterManagerAddOnList{ListMeta: obj.(*v1alpha1.ClusterManagerAddOnList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterManagerAddOnList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterManagerAddOns.
func (c *FakeClusterManagerAddOns) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clustermanageraddonsResource, opts))
}

// Create takes the representation of a clusterManagerAddOn and creates it.  Returns the server's representation of the clusterManagerAddOn, and an error, if there is any.
func (c *FakeClusterManagerAddOns) Create(ctx context.Context, clusterManagerAddOn *v1alpha1.ClusterManagerAddOn, opts v1.CreateOptions) (result *v1alpha1.ClusterManagerAddOn, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clustermanageraddonsResource, clusterManagerAddOn), &v1alpha1.ClusterManagerAddOn{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterManagerAddOn), err
}

// Update takes the representation of a clusterManagerAddOn and updates it. Returns the server's representation of the clusterManagerAddOn, and an error, if there is any.
func (c *FakeClusterManagerAddOns) Update(ctx context.Context, clusterManagerAddOn *v1alpha1.ClusterManagerAddOn, opts v1.UpdateOptions) (result *v1alpha1.ClusterManagerAddOn, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clustermanageraddonsResource, clusterManagerAddOn), &v1alpha1.ClusterManagerAddOn{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterManagerAddOn), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterManagerAddOns) UpdateStatus(ctx context.Context, clusterManagerAddOn *v1alpha1.ClusterManagerAddOn, opts v1.UpdateOptions) (*v1alpha1.ClusterManagerAddOn, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(clustermanageraddonsResource, "status", clusterManagerAddOn), &v1alpha1.ClusterManagerAddOn{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterManagerAddOn), err
}

// Delete takes name of the clusterManagerAddOn and deletes it. Returns an error if one occurs.
func (c *FakeClusterManagerAddOns) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(clustermanageraddonsResource, name), &v1alpha1.ClusterManagerAddOn{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterManagerAddOns) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clustermanageraddonsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterManagerAddOnList{})
	return err
}

// Patch applies the patch and returns the patched clusterManagerAddOn.
func (c *FakeClusterManagerAddOns) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterManagerAddOn, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clustermanageraddonsResource, name, pt, data, subresources...), &v1alpha1.ClusterManagerAddOn{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterManagerAddOn), err
}
